name: Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make
        
    - name: Compile and run tests
      working-directory: tests
      run: |
        g++ -std=c++11 -Wall -Wextra -O2 -I.. \
          ../model/neural_components/*.cpp \
          ../model/activation_functions/*.cpp \
          ../controller/*.cpp \
          ../utils/*.cpp \
          ../importer/*.cpp \
          ../exporter/*.cpp \
          NeuralNetworkTester.cpp -o test.exe
        ./test.exe
